# Generated by Django 5.2 on 2025-04-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Mission', max_length=200)),
                ('hero_subtitle', models.TextField(default="At Gitako, we're on a mission to empower farmers with technology that makes agriculture more productive, profitable, and sustainable.")),
                ('hero_description', models.TextField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/about/')),
                ('story_title', models.CharField(default='Our Story', max_length=100)),
                ('story_subtitle', models.TextField(default='Gitako was born from a simple observation: farmers need better tools to manage their operations in the digital age.')),
                ('team_title', models.CharField(default='Meet Our Team', max_length=100)),
                ('values_title', models.CharField(default='Our Values', max_length=100)),
                ('cta_text', models.CharField(default='Join the Gitako Community', max_length=100)),
                ('cta_subtitle', models.TextField(default='Be part of our mission to transform agriculture through technology.')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Material icon name (e.g., 'agriculture')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Value',
                'verbose_name_plural': 'Company Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact FAQ',
                'verbose_name_plural': 'Contact FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Get in Touch', max_length=200)),
                ('hero_subtitle', models.TextField(default="Have questions about Gitako? We're here to help. Reach out to our team using any of the methods below.")),
                ('office_address', models.TextField(default='123 Farm Street\nNairobi, Kenya\n00100')),
                ('phone_number', models.CharField(default='+254 700 123 456', max_length=20)),
                ('office_hours', models.CharField(default='Monday - Friday\n9:00 AM - 5:00 PM EAT', max_length=100)),
                ('email_general', models.EmailField(default='info@gitako.com', max_length=254)),
                ('email_support', models.EmailField(default='support@gitako.com', max_length=254)),
                ('form_title', models.CharField(default='Send Us a Message', max_length=100)),
                ('map_embed_url', models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.8177928497174!2d36.8170119!3d-1.2830983!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f10a22f8b05c5%3A0xece6bb3dea6c8c8c!2sNairobi%2C%20Kenya!5e0!3m2!1sen!2sus!4v1625123456789!5m2!1sen!2sus')),
                ('faq_title', models.CharField(default='Frequently Asked Questions', max_length=100)),
                ('cta_text', models.CharField(default='Ready to Get Started?', max_length=100)),
                ('cta_subtitle', models.TextField(default='Join thousands of farmers who are already using Gitako to improve their productivity and profitability.')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Material icon name (e.g., 'landscape')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='site/feature_details/')),
                ('bullet_points', models.TextField(help_text='Enter bullet points separated by new lines')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Detail',
                'verbose_name_plural': 'Feature Details',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Powerful Features for Modern Farming', max_length=200)),
                ('hero_subtitle', models.TextField(default='Gitako provides a comprehensive suite of tools designed specifically for farmers to manage their operations efficiently and increase productivity.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/features/')),
                ('cta_text', models.CharField(default='Ready to Transform Your Farm?', max_length=100)),
                ('cta_subtitle', models.TextField(default='Join thousands of farmers who are already using Gitako to improve their productivity and profitability.')),
            ],
            options={
                'verbose_name': 'Features Page',
                'verbose_name_plural': 'Features Page',
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='site/hero_slider/')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pricing FAQ',
                'verbose_name_plural': 'Pricing FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Simple, Transparent Pricing', max_length=200)),
                ('hero_subtitle', models.TextField(default="Choose the plan that fits your farm's needs. All plans include core features with different limits and capabilities.")),
                ('faq_title', models.CharField(default='Frequently Asked Questions', max_length=100)),
                ('cta_text', models.CharField(default='Still Have Questions?', max_length=100)),
                ('cta_subtitle', models.TextField(default='Our team is ready to help you choose the right plan for your farm.')),
            ],
            options={
                'verbose_name': 'Pricing Page',
                'verbose_name_plural': 'Pricing Page',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField(help_text="Enter features separated by new lines. Prefix with '-' for inactive features.")),
                ('is_popular', models.BooleanField(default=False)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Gitako', max_length=100)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('hero_title', models.CharField(default='Smart Farm Management', max_length=200)),
                ('hero_subtitle', models.TextField(default='Gitako helps you manage your farm operations efficiently, track activities, monitor inventory, and maximize profits with data-driven insights.')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('footer_text', models.CharField(default='© Gitako. All rights reserved.', max_length=200)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Story Section',
                'verbose_name_plural': 'Story Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='site/team/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='site/testimonials/')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
