# Generated by Django 5.2 on 2025-04-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_alter_contactpage_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.8177928497174!2d36.8170119!3d-1.2830983!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f10a22f8b05c5%3A0xece6bb3dea6c8c8c!2sNairobi%2C%20Kenya!5e0!3m2!1sen!2sus!4v1625123456789!5m2!1sen!2sus', max_length=400),
        ),
    ]
