# Generated by Django 5.2 on 2025-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_alter_contactpage_map_embed_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='maintenance_message',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='contact_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='maintenance_mode',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Gitako Farm Management', max_length=100),
        ),
    ]
