# Generated by Django 5.2 on 2025-06-12 12:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_rename_email_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storysection',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
