# Generated by Django 5.2 on 2025-06-12 16:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0006_alter_storysection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
