# Generated by Django 5.2 on 2025-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0007_alter_teammember_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storysection',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(),
        ),
    ]
