# Generated by Django 5.2 on 2025-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='variance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='item_type',
            field=models.CharField(choices=[('', 'Select Type'), ('income', 'Income'), ('expense', 'Expense')], default='', max_length=10),
        ),
    ]
