# Generated by Django 5.2 on 2025-04-13 09:32

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('growing_season', models.CharField(blank=True, max_length=100)),
                ('average_growing_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('ideal_temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ideal_temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ideal_rainfall_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ideal_rainfall_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ideal_soil_ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ideal_soil_ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('maturity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('yield_potential', models.CharField(blank=True, max_length=100)),
                ('disease_resistance', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='farms.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop varieties',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('farm_type', models.CharField(choices=[('crop', 'Crop Farm'), ('livestock', 'Livestock Farm'), ('mixed', 'Mixed Farm'), ('aquaculture', 'Aquaculture'), ('poultry', 'Poultry'), ('orchard', 'Orchard'), ('vineyard', 'Vineyard'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in acres', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.get_file_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Farm Manager'), ('worker', 'Farm Worker'), ('specialist', 'Specialist'), ('seasonal', 'Seasonal Worker'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_employments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in acres', max_digits=10)),
                ('crop_type', models.CharField(blank=True, max_length=255, null=True)),
                ('livestock_type', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.get_file_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('expected_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='farms.crop')),
                ('crop_variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_cycles', to='farms.cropvariety')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='farms.farmsection')),
            ],
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nitrogen_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('phosphorus_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('potassium_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('organic_matter_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcium_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('magnesium_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sulfur_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('zinc_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('manganese_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('iron_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('copper_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('boron_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('texture', models.CharField(blank=True, max_length=100)),
                ('cec', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('laboratory', models.CharField(blank=True, max_length=255)),
                ('test_method', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_tests', to='farms.farmsection')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=50)),
                ('data_source', models.CharField(choices=[('manual', 'Manual Entry'), ('weather_station', 'Weather Station'), ('api', 'Weather API')], default='api', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='farms.farm')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('farm', 'date')},
            },
        ),
    ]
