# Generated by Django 5.2 on 2025-04-13 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('land_clearing', 'Land Clearing'), ('land_preparation', 'Land Preparation'), ('planting', 'Planting'), ('fertilizer', 'Fertilizer Application'), ('pest_control', 'Pest Control'), ('weed_control', 'Weed Control'), ('irrigation', 'Irrigation'), ('harvesting', 'Harvesting'), ('other', 'Other')], max_length=20)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('crop_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.cropcycle')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.farmsection')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FertilizerActivity',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activities.activity')),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('application_method', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestActivity',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activities.activity')),
                ('yield_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_unit', models.CharField(max_length=50)),
                ('quality_grade', models.CharField(blank=True, max_length=50)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationActivity',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activities.activity')),
                ('irrigation_method', models.CharField(max_length=100)),
                ('water_source', models.CharField(blank=True, max_length=100)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('water_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_unit', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PestControlActivity',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activities.activity')),
                ('product_name', models.CharField(max_length=100)),
                ('target_pest', models.CharField(blank=True, max_length=100)),
                ('application_method', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlantingActivity',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activities.activity')),
                ('seed_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seed_unit', models.CharField(max_length=50)),
                ('planting_method', models.CharField(blank=True, max_length=100)),
                ('spacing', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='activities.activity')),
            ],
            options={
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
    ]
