# Generated by Django 5.2 on 2025-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('', 'Select Activity Type'), ('land_clearing', 'Land Clearing'), ('land_preparation', 'Land Preparation'), ('planting', 'Planting'), ('fertilizer', 'Fertilizer Application'), ('pest_control', 'Pest Control'), ('weed_control', 'Weed Control'), ('irrigation', 'Irrigation'), ('harvesting', 'Harvesting'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('', 'Select Status'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='', max_length=20),
        ),
    ]
